apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.agentConfigName }}
  labels:
    {{- include "subscriber.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
data: {}
