{{- if not .Values.useExistingInfraSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.global.infraSecretName }}
  labels:
    {{- include "subscriber.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
data: 
  INFRA_ID: {{ .Values.INFRA_ID | b64enc | quote }}
  ACCESS_KEY: {{.Values.ACCESS_KEY | b64enc | quote }}
{{ end }}
