apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus-agent.serviceAccountName" . }}
  labels:
    {{- include "litmus-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "litmus-agent.serviceAccountName" . }}
  labels:
    {{- include "litmus-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "litmus-agent.serviceAccountName" . }}
  labels:
    {{- include "litmus-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "litmus-agent.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "litmus-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
