{{ if not (has "pod-network-latency" .Values.experiments.disabled) }}
---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Injects network latency on pods belonging to an app deployment
kind: ChaosExperiment
metadata:
  name: {{ include "kubernetes-chaos.name" . }}-pod-network-latency
  labels:
    instance: {{ .Release.Name }}
    chart: {{ include "kubernetes-chaos.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
    image: "{{ .Values.image.litmusGO.repository }}:{{ .Values.image.litmusGO.tag }}"
    imagePullPolicy: {{ .Values.image.litmusGO.pullPolicy }}
    args:
    - -c
    - ./experiments/pod-network-latency
    command:
    - /bin/bash
    env:

    - name: TARGET_CONTAINER
      value: ''

    - name: NETWORK_INTERFACE
      value: 'eth0'

    - name: TC_IMAGE
      value: "{{ .Values.image.networkChaos.tcImage }}"

    # provide lib image
    - name: LIB_IMAGE
      value: "{{ .Values.image.litmusLIBImage.repository }}:{{ .Values.image.litmusLIBImage.tag }}"

    - name: NETWORK_LATENCY
      value: '60000' #in ms

    - name: TOTAL_CHAOS_DURATION
      value: '60' # in seconds

    # Time period to wait before injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    - name: LIB
      value: 'pumba'
    labels:
      name: pod-network-latency
{{ end }}
