---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-aws.name" . }}-chaos-admin 
  labels:
    {{- include "kube-aws.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-aws.name" . }}-chaos-admin
subjects:
- kind: ServiceAccount
  name: {{ include "kube-aws.name" . }}-chaos-admin
  namespace: {{ .Release.Namespace }}
