{{- if and .Values.internalTLS.enabled }}
{{- if eq .Values.internalTLS.certSource "manual" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "litmus-portal.internalTLS.authServer.secretName" . }}"
  labels:
{{ include "litmus-portal.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ (required "The \"internalTLS.trustCa\" is required!" .Values.internalTLS.trustCa) | b64enc | quote }}
  tls.crt: {{ (required "The \"internalTLS.authServer.crt\" is required!" .Values.internalTLS.authServer.crt) | b64enc | quote }}
  tls.key: {{ (required "The \"internalTLS.authServer.key\" is required!" .Values.internalTLS.authServer.key) | b64enc | quote }}
{{- end }}
{{- end }}
