{{ if and ( or (eq .Values.operatorMode "standard") (eq .Values.operatorMode "admin")) ( .Values.rbac.create ) }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "litmus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ if and (eq .Values.operatorMode "admin") ( .Values.rbac.create ) }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    name: {{ include "litmus.name" . }}-admin
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "litmus.fullname" . }}-admin
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.serviceAccountName" . }}-admin
  namespace: {{ .Release.Namespace }}
{{ end }}
