{{ if or (eq .Values.operatorMode "standard") (eq .Values.operatorMode "admin") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    app: {{ template "litmus.name" . }}
    {{- include "litmus.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "litmus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ if eq .Values.operatorMode "admin" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    app: {{ template "litmus.name" . }}
    {{- include "litmus.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "litmus.fullname" . }}-admin
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
{{ end }}
