apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    chart: {{ include "litmus.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "litmus.name" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ include "litmus.name" . }}
        instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "litmus.fullname" . }}
      containers:
        - name: {{ .Values.operatorName }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          command:
          - chaos-operator
          env:
            - name: CHAOS_RUNNER_IMAGE
              value: "{{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag }}"
          {{ if or (eq .Values.operatorMode "namespaced") ( eq .Values.operatorMode "admin") }}    
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{ else }}
            - name: WATCH_NAMESPACE
              value: 
          {{ end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-operator"
          {{- if .Values.policies.monitoring.disabled }}
            - name: ANALYTICS
              value: "FALSE"
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
