apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litmus.fullname" . }} 
  labels:
    name: {{ include "litmus.name" . }}
    chart: {{ include "litmus.chart" . }}
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "litmus.name" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ include "litmus.name" . }}
        instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "litmus.fullname" . }} 
      containers:
        - name: {{ .Values.operatorName }}
          image: "{{ .Values.image.operator.repository }}:{{ .Values.image.operator.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
          - chaos-operator
          env:
            - name: CHAOS_RUNNER_IMAGE
              value: "{{ .Values.image.runner.repository }}:{{ .Values.image.runner.tag }}"
            - name: CHAOS_MONITOR_IMAGE
              value: "{{ .Values.image.exporter.repository }}:{{ .Values.image.exporter.tag }}"
            - name: WATCH_NAMESPACE
              value:  
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-operator"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
