{{- if .Values.exporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmus.name" . }}-monitor
  labels:
    name: {{ include "litmus.name" . }}-monitor
    chart: {{ include "litmus.chart" . }}
    instance: {{ .Release.Name }}
    litmuschaos.io/version: {{ .Chart.AppVersion }} 
{{- if .Values.exporter.service.annotations }}
  annotations:
    {{- toYaml .Values.exporter.service.annotations | nindent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.exporter.service.port }}
    protocol: TCP
    targetPort: http
  type: {{ .Values.exporter.service.type }}
  selector:
    name: {{ include "litmus.name" . }}-monitor
    instance: {{ .Release.Name }}
{{- end -}}
