{{- if .Values.portal.frontend.virtualService.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: litmusportal-frontend-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-frontend
    {{- include "litmus-portal.labels" . | nindent 4 }}
spec:
  hosts:
{{- with .Values.portal.frontend.virtualService.hosts }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  gateways:
{{- with .Values.portal.frontend.virtualService.gateways }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  http:
{{- if .Values.portal.frontend.virtualService.pathPrefixEnabled }}
  - match:
    - uri:
        prefix: /litmuschaos
    rewrite:
      uri: "/"
    route:
{{- else }}
  - route:
{{- end }}
    - destination:
        host:  {{ include "litmus-portal.fullname" . }}-frontend-service
        port:
          number: {{ .Values.portal.frontend.service.port }}
{{- end -}}
