apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmus-portal.fullname" . }}-frontend-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-frontend
    {{- include "litmus-portal.labels" . | nindent 4 }}
  {{- with .Values.portal.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.portal.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.portal.frontend.service.port }}
      targetPort: {{ .Values.portal.frontend.service.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-frontend
