{{- if .Values.upgradeAgent.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "litmus-portal.fullname" . }}-upgrade-agent-cp-{{.Release.Revision}}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: {{ .Values.upgradeAgent.controlPlane.restartPolicy }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: upgrade-agent
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.upgradeAgent.controlPlane.image.repository }}:{{ .Values.upgradeAgent.controlPlane.image.tag }}
          imagePullPolicy: {{ .Values.upgradeAgent.controlPlane.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "litmus-portal.secretname" . }}
            - configMapRef:
                name: {{ include "litmus-portal.fullname" . }}-admin-config
          env:
            - name: DB_PASSWORD
              {{- if .Values.mongodb.enabled }}
              {{- if not .Values.mongodb.auth.existingSecret }}
              value: {{ .Values.mongodb.auth.rootPassword }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.existingSecret }}
                  key: mongodb-root-password
              {{- end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_PASSWORD
              {{- end }}
            - name: DB_USER
              {{- if .Values.mongodb.enabled }}
              value: {{ .Values.mongodb.auth.rootUser }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_USER
              {{- end }}
          resources:
            {{- toYaml .Values.upgradeAgent.resources | nindent 12 }}
    {{- with .Values.upgradeAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.upgradeAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.upgradeAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
