{{ if eq .Values.portalScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: litmus-server-crb-for-{{ include "litmus-portal.fullname" . }}-server
  labels:
    app.kubernetes.io/component: litmus-server-crb-for-{{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litmus-server-cr-for-{{ include "litmus-portal.fullname" . }}-server
subjects:
  - kind: ServiceAccount
    name: {{ .Values.portal.server.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{ end }}
