{{ if eq .Values.portalScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: litmus-server-cr-for-{{ include "litmus-portal.fullname" . }}-server
  labels:
    app.kubernetes.io/component: litmus-server-cr-for-{{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
rules:
  - apiGroups: [networking.k8s.io, extensions]
    resources: [ingresses]
    verbs: [get]
  - apiGroups: [""]
    resources: [services, nodes, pods/log]
    verbs: [get, watch]
  - apiGroups: [""] # To get TLS Cert from secrets incase of cluster scope
    resources: [secrets]
    verbs: [get]
{{ end }}
