apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
  {{- with .Values.portal.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.portal.server.service.type }}
  {{- end }}
  ports:
    - name: graphql-server
      port: {{ .Values.portal.server.service.graphqlServer.port }}
      targetPort: {{ .Values.portal.server.service.graphqlServer.targetPort }}
    - name: graphql-rpc-server
      port: {{ .Values.portal.server.service.graphqlRpcServer.port }}
      targetPort: {{ .Values.portal.server.service.graphqlRpcServer.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
