{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus-server-role-for-{{ include "litmus-portal.fullname" . }}-server
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: litmus-server-role-for-{{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
rules:
  - apiGroups: [networking.k8s.io, extensions]
    resources: [ingresses]
    verbs: [get]
  - apiGroups: [""]
    resources: [services,  pods/log]
    verbs: [get, watch]
{{ end }}
