{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-server-rb-for-{{ include "litmus-portal.fullname" . }}-server
  namespace:  {{ .Release.Namespace }}
  labels:
    name: litmus-server-rb-for-{{ include "litmus-portal.name" . }}-server
    app.kubernetes.io/component: litmus-server-rb-for-{{ include "litmus-portal.name" . }}-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-server-role-for-{{ include "litmus-portal.fullname" . }}-server
subjects:
  - kind: ServiceAccount
    name: {{ .Values.portal.server.serviceAccountName }}
    namespace:  {{ .Release.Namespace }}
{{ end }}
