{{- if .Values.ingress.enabled -}}
{{ $fullName := include "litmus-portal.fullname" . }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}-frontend
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-frontend
    {{- include "litmus-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations.frontend }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range.Values.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host | quote }}
    http:
  {{- else }}
  - http: 
  {{- end }}
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: litmusportal-frontend-service
            port:
              number: 9091
    {{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
      paths:
      - path: /
        backend:
          serviceName: litmusportal-frontend-service
          servicePort: 9091
    {{- end }}
  {{- end }}
---
{{- if .Values.ingress.enabled -}}
{{ $fullName := include "litmus-portal.fullname" . }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}-backend
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-backend
    {{- include "litmus-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations.backend }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range.Values.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host | quote }}
    http:
  {{- else }}
  - http: 
  {{- end }}
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      paths:
      - path: /backend/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: litmusportal-server-service
            port:
              number: 9002
    {{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
      paths:
      - path: /backend/(.*)
        backend:
          serviceName: litmusportal-server-service
          servicePort: 9002
    {{- end }}
  {{- end }}
