apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "litmus-portal.fullname" . }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-database
    {{- include "litmus-portal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-database
  serviceName: mongo
  replicas: {{ .Values.mongo.replicas }}
  template:
    metadata:
      labels:
        app: mongo
        app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-database
        {{- include "litmus-portal.labels" . | nindent 8 }}
    spec:
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: mongo
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
              name: http
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "litmus-portal.fullname" . }}-admin-config
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "litmus-portal.fullname" . }}-admin-config
                  key: DB_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        {{- if .Values.mongo.persistence.storageClass }}
        storageClassName: {{ .Values.mongo.persistence.storageClass }}
        {{- end }}
        accessModes:
          - {{ .Values.mongo.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.mongo.persistence.size }}