{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server-rb
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.portal.server.serviceAccountName }}
    namespace:  {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "litmus-portal.fullname" . }}-server
  apiGroup: rbac.authorization.k8s.io
{{ end }}
