{{- if and .Values.serviceAccount.create ( eq .Values.global.INFRA_MODE "cluster") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chaos-exporter.serviceAccountName" . }}
  labels:
    {{- include "chaos-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chaos-exporter.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "chaos-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
