adminConfig:
  VERSION: "ci"

upgradeAgent:
  controlPlane:
    image:
      tag: "ci"

portal:
  frontend:
    image:
      tag: ci

  server:
    graphqlServer:
      image:
        tag: ci
      imageEnv:
        SUBSCRIBER_IMAGE: "litmusportal-subscriber:ci"
        EVENT_TRACKER_IMAGE: "litmusportal-event-tracker:ci"
        LITMUS_CHAOS_OPERATOR_IMAGE: "chaos-operator:ci"
        LITMUS_CHAOS_RUNNER_IMAGE: "chaos-runner:ci"
        LITMUS_CHAOS_EXPORTER_IMAGE: "chaos-exporter:ci"

    authServer:
      image:
        tag: ci

# -- Configure the Bitnami MongoDB subchart
# see values at https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
mongodb:
  enabled: true
  auth:
    enabled: true
    rootPassword: "superhardpassword"
    # -- existingSecret Existing secret with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, ` mongodb-replica-set-key`)
    existingSecret: ""
  architecture: standalone
  useStatefulSet: false
  replicaCount: 1
  metrics:
    enabled: false
    prometheusRule:
      enabled: false