apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litmus-portal.fullname" . }}-frontend
  namespace:  {{ .Release.Namespace }}
  labels:
    component: litmusportal-frontend
spec:
  replicas: {{ .Values.portal.frontend.replicas }}
  selector:
    matchLabels:
      component: litmusportal-frontend
  template:
    metadata:
      labels:
        component: litmusportal-frontend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: litmusportal-frontend
          image: {{ .Values.portal.frontend.image.repository }}:{{ .Values.portal.frontend.image.tag }}
          imagePullPolicy: {{ .Values.portal.frontend.image.pullPolicy }}
          resources:
            {{- toYaml .Values.portal.frontend.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.portal.frontend.containerPort }}
              name: http
          env:
            - name: AGENT_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "litmus-portal.fullname" . }}-admin-config
                  key: AgentScope
