{{- $values := .Values.mongoDB.deployment.persistence -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: {{ .Values.portalNamespace }}
  labels:
    app: mongo
spec:
  accessModes:
    - {{ $values.accessMode }}
  resources:
    requests:
      storage: {{ $values.size }}
  {{- if $values.storageClass }}
  storageClassName: {{ $values.storageClass }}
  {{- end }}