apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.mongoDB.service.port }}
      targetPort: {{ .Values.mongoDB.service.targetPort }}
  selector:
    component: database