apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmus-portal.fullname" . }}-mongo
  namespace:  {{ .Release.Namespace }}
  labels:
    app: mongo
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  selector:
    component: database
