apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-frontend
  namespace:  {{ .Release.Namespace }}
  labels:
    component: litmusportal-frontend
spec:
  replicas: {{ .Values.portalFrontend.deployment.replicas }}
  selector:
    matchLabels:
      component: litmusportal-frontend
  template:
    metadata:
      labels:
        component: litmusportal-frontend
    spec:
      containers:
        - name: litmusportal-frontend
          image: {{ .Values.portalFrontend.deployment.image }}
          imagePullPolicy: {{ .Values.portalFrontend.deployment.imagePullPolicy }}
          resources:
            {{- toYaml .Values.portalFrontend.deployment.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.portalFrontend.deployment.port }}
          env:
            - name: AGENT_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: AgentScope