{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server
  namespace:  {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
{{ end }}
