apiVersion: v1
appVersion: "1.10.0"
description: A Helm chart to install litmus portal
name: litmus-portal
version: 1.10.1
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: rajdas98
    email: raj.das@mayadata.io
  - name: ispeakc0de
    email: shubham.chaudhary@mayadata.io
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
