{{- if .Values.exporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmus.name" . }}-monitor
  labels:
    {{- include "litmus.exporterLabels" . | nindent 4 }}
{{- if .Values.exporter.service.annotations }}
  annotations:
    {{- toYaml .Values.exporter.service.annotations | nindent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.exporter.service.port }}
    protocol: TCP
    targetPort: http
  type: {{ .Values.exporter.service.type }}
  selector:
    {{- include "litmus.exporterSelectors" . | nindent 4 }}
{{- end -}}
