{{ if eq .Values.operatorMode "namespaced" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    {{- include "litmus.operatorLabels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "litmus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
