apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    {{- include "litmus.operatorLabels" . | indent 4 }}
{{ if eq .Values.operatorMode "admin" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    {{- include "litmus.operatorLabels" . | indent 4 }}
{{ end }}
