apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    app: {{ template "litmus.name" . }}
    {{- include "litmus.labels" . | indent 4 }}
{{ if eq .Values.operatorMode "admin" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    app: {{ template "litmus.name" . }}
    {{- include "litmus.labels" . | indent 4 }}
{{ end }}
