{{- if and .Values.serviceAccount.create ( eq .Values.global.INFRA_MODE "namespace") -}}
# required or runner and experiment pods
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chaos-operator.serviceAccountName" . }}-litmus-admin
  labels:
    {{- include "chaos-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chaos-operator.serviceAccountName" . }}-litmus-admin
subjects:
  - kind: ServiceAccount
    name: litmus-admin
    namespace: {{ .Release.Namespace }}
{{- end }}
