{{- if and .Values.serviceAccount.create ( eq .Values.global.INFRA_MODE "cluster") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "workflow-controller.serviceAccountName" . }}-argo-chaos
rules:
  # for managing the pods created by workflow controller to implement individual steps in the workflow
  - apiGroups: ['']
    resources: ['pods', 'services', 'namespaces']
    verbs: ['create', 'get', 'watch', 'patch', 'delete', 'list']

  # for tracking & getting logs of the pods created by workflow controller to implement individual steps in the workflow
  - apiGroups: ['']
    resources: ['pods/log', 'secrets', 'configmaps']
    verbs: ['get', 'watch', 'create', 'delete', 'patch']

  # for creation & deletion of application in predefined workflows
  - apiGroups: ['apps']
    resources: ['deployments', 'statefulsets']
    verbs: ['get', 'watch', 'patch' , 'create', 'delete']
    
  # for creation, status polling and deletion of litmus chaos resources used within a chaos workflow
  - apiGroups: ['litmuschaos.io']
    resources: ['chaosengines', 'chaosexperiments', 'chaosresults', 'chaosschedules']
    verbs: ['create', 'list', 'get', 'patch', 'delete', 'watch']
{{- end }}
