{{- if and .Values.serviceAccount.create ( eq .Values.global.AGENT_MODE "cluster") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "workflow-controller.serviceAccountName" . }}-argo-chaos
  labels:
    {{- include "workflow-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "workflow-controller.serviceAccountName" . }}-argo-chaos
subjects:
  - kind: ServiceAccount
    name: argo-chaos
    namespace: {{ .Release.Namespace }}
{{- end }}
