{{- if and .Values.serviceAccount.create ( eq .Values.global.AGENT_MODE "namespace") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "workflow-controller.serviceAccountName" . }}
  labels:
    {{- include "workflow-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "workflow-controller.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "workflow-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
