apiVersion: v1
appVersion: "2.9.0"
description: A Helm chart to install litmus Azure chaos experiments
name: kube-azure
version: 2.9.0
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - azure
  - kubernetes
maintainers:
  - name: jasstkn
    email: jasssstkn@yahoo.com
  - name: ksatchit
    email: karthik@chaosnative.com
  - name: uditgaurav
    email: udit@chaosnative.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
